# Pima Alarm Sensors
sensor:
  - name: "Alarm Open Zones"
    platform: mqtt
    state_topic: "pima_alarm/status"
    value_template: "{{ value_json['open zones'] }}"
  - name: "Alarm Alarmed Zones"
    platform: mqtt
    state_topic: "pima_alarm/status"
    value_template: "{{ value_json['alarmed zones'] }}"
  - name: "Alarm Arm State"
    platform: mqtt
    state_topic: "pima_alarm/status"
    value_template: "{{ value_json['partitions']['1'] }}"
